In [12]:
import numpy as np


## Criando um objeto array do tipo numpy

In [29]:
lista = [4, 8, 2, 12, 5, 8, 0]

arraylista = np.array(lista)

In [30]:
arraylista

array([ 4,  8,  2, 12,  5,  8,  0])

## Formas de se criar um array:

In [15]:
# 1. np.zeros((i,j)) onde i são linhas e j colunas preenchidas com zero

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# 2. np.arange(x), onde será criado um array com valores de 0 a x-1

np.arange(13)
np.arange(4,13,2) #começa no 4, vai até 13-1, no passo de 2 em 2

array([ 4,  6,  8, 10, 12])

In [19]:
# 3. np.random.random((i,j)), gera números de ponto flutuante entre 0.0 e 1.0

np.random.random(4)

array([0.03644768, 0.52642935, 0.44716611, 0.47651405])

## Exercícios!

In [21]:
# 1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.

np.random.random((4,3))

array([[0.94992999, 0.15816372, 0.98733631],
       [0.0841886 , 0.47970539, 0.02207724],
       [0.59763943, 0.36898487, 0.97626191],
       [0.50405931, 0.29826746, 0.42621193]])

In [26]:
# 2. Crie um array com valores inteiros e aleatórios contendo 3 linhas e 5 colunas.
np.random.randint(30,size=(3,5))

array([[21, 15, 23,  3, 23],
       [ 4,  2, 21,  1,  3],
       [ 0, 13,  3,  3,  4]])

In [27]:
# 3. Crie um array com 5 colunas e 10 linhas inicializados com zeros.
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Arrays com 3 dimensões

In [32]:
# Criando arrays com 2 dimensões
# Primeira dimensão é a linha e Segunda dimensão é a coluna
arr1_2d = [[1,2],[3,4]]
arr2_2d = [[5,6],[7,8]]
arr3_2d = [[9,2],[5,8]]

# Criando array 3D
array_3d = np.array([arr1_2d, arr2_2d, arr3_2d])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [5, 8]]])

## Dimensões do array (atributos e métodos)

In [33]:
# Atributos: propriedades, caracteristícas do objetos
# .shape: descreve a forma do array

# Métodos: Executam uma ação
# .flatten(): achata o array
# .reshape(): transforma as dimensões do array

In [41]:
# Exemplo

array_am = np.random.randint(50, size = (2,6))
array_am

array([[12, 44, 26, 17, 19, 39],
       [18,  3, 20,  5, 21,  6]])

In [42]:
# Mostrando a dimensão do array
array_am.shape

(2, 6)

In [43]:
# Achatando o array para uma única dimensão
array_am.flatten()

array([12, 44, 26, 17, 19, 39, 18,  3, 20,  5, 21,  6])

In [45]:
# Tranformando a dimensão do array
# Obs: para transformar, a nova dimensão deve conter o mesmo número de elementos
array_am.reshape(4,3)

array([[12, 44, 26],
       [17, 19, 39],
       [18,  3, 20],
       [ 5, 21,  6]])

## Exercícios

In [54]:
# 1. Reduza o array (5,7) a apenas uma dimensão

array57 = np.random.randint(100, size=(5,7))
array57

array57.flatten()

array([96, 54, 37, 35, 59, 62, 17, 96, 87, 74, 35,  4, 89, 29, 57, 59, 35,
       52, 51,  9,  9, 44, 97,  1, 35, 43, 60,  7, 17, 22, 59, 97, 73, 83,
       58])

In [55]:
# 2. Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. 
# Os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números (4,3).
# Crie um array que represente esse jogo.

bingo = np.random.randint(1,31, size = (10, 4,3))
bingo

array([[[11,  3, 15],
        [ 2, 10,  7],
        [ 9, 22, 13],
        [ 6, 24, 27]],

       [[19, 23, 23],
        [28, 12, 29],
        [22, 11, 18],
        [30, 26, 10]],

       [[25, 29, 17],
        [ 9, 17, 15],
        [ 1, 20,  9],
        [ 3, 15, 27]],

       [[17, 14, 25],
        [ 6,  6, 20],
        [ 3,  2,  5],
        [ 8,  4,  8]],

       [[11, 23, 19],
        [ 4, 29, 19],
        [12,  1,  3],
        [25, 10, 17]],

       [[ 4, 26, 20],
        [22, 23, 16],
        [ 5, 10,  4],
        [29, 15,  2]],

       [[11,  9, 29],
        [15, 26, 10],
        [26,  2, 17],
        [22, 11,  8]],

       [[25, 20,  4],
        [25,  3, 25],
        [ 9, 24, 13],
        [ 4,  9, 18]],

       [[29,  2,  1],
        [ 3,  4, 18],
        [27, 28, 24],
        [14,  2,  7]],

       [[30, 14, 10],
        [21,  8, 26],
        [23, 29, 20],
        [18, 17, 16]]])

In [57]:
# 3. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas. 
bingo_transformado = bingo.reshape((5,4,6))
bingo_transformado

array([[[11,  3, 15,  2, 10,  7],
        [ 9, 22, 13,  6, 24, 27],
        [19, 23, 23, 28, 12, 29],
        [22, 11, 18, 30, 26, 10]],

       [[25, 29, 17,  9, 17, 15],
        [ 1, 20,  9,  3, 15, 27],
        [17, 14, 25,  6,  6, 20],
        [ 3,  2,  5,  8,  4,  8]],

       [[11, 23, 19,  4, 29, 19],
        [12,  1,  3, 25, 10, 17],
        [ 4, 26, 20, 22, 23, 16],
        [ 5, 10,  4, 29, 15,  2]],

       [[11,  9, 29, 15, 26, 10],
        [26,  2, 17, 22, 11,  8],
        [25, 20,  4, 25,  3, 25],
        [ 9, 24, 13,  4,  9, 18]],

       [[29,  2,  1,  3,  4, 18],
        [27, 28, 24, 14,  2,  7],
        [30, 14, 10, 21,  8, 26],
        [23, 29, 20, 18, 17, 16]]])

## Tipo de dados em NumPy

In [ ]:
# np.int64: valores inteiros de até 64 bits
# np.int32: valores inteiros de até 3 bits
# np.float64: valores de ponto flutuante de até 64 bits
# np.int32: valores de ponto flutuante de até 32 bits

# Podemos verificar o tipo do array pelo atributo .dtype

In [58]:
# Exemplos

np.array([2.14, 6.25, 160.87, 8.4]).dtype

dtype('float64')

In [59]:
np.array([2, 6, 160, 8]).dtype

dtype('int64')

In [61]:
# No caso de string, ele apresentará o tamanho da maior string
np.array(["Ola", "Codigo", "Mulheres", "Python"]).dtype

dtype('<U8')

## Conversão dos Dados

In [63]:
# dtype como argumento

arr_float32 = np.array([2.14, 6.25, 160.87], dtype = np.float32)
arr_float32.dtype

dtype('float32')

In [67]:
# Conversão com astype
arr_vf = np.array([[True, False], [False, False]], dtype = np.bool8)
arr_vf = arr_vf.astype(np.int32)
arr_vf.dtype

/var/folders/jz/925s2xqx5rg2bqxv7_55d0nc0000gn/T/ipykernel_2631/2384465621.py:2: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  arr_vf = np.array([[True, False], [False, False]], dtype = np.bool8)


dtype('int32')

In [68]:
# Coerção dos dados: uma conversão automática levando em consideração o tipo dominante do array

np.array([3, 5, 6.7]).dtype

dtype('float64')

In [69]:
# Nesse caso, o tipo dominante é String
np.array(["pedra", False, 2, 6.57]).dtype

dtype('<U32')

## Index em array

In [70]:
# Index sempre inicia do zero
arr_index = np.array([2,4,8,-1])
arr_index[1]

4

In [77]:
# Index em array com 2 dimensões
arr_index2d = np.array([
                [2,3,5,4],
                [9,10,-1,0],
                [3,12,-4,8],
                [0, 6, 7, -2]])
arr_index2d[1,2]

-1

In [78]:
# Seleciona uma linha do array de 2 dimensões
arr_index2d[0]

array([2, 3, 5, 4])

In [79]:
# Seleciona uma coluna do array de 2 dimensões
arr_index2d[:,1]

array([ 3, 10, 12,  6])

In [80]:
# A partir dos índices, conseguimos realizar fatiamento (slicing) 

#No caso abaixo, foi fatiada da linha 1 a 2 e coluna 0 a 1
arr_index2d[1:3, 0:2]

array([[ 9, 10],
       [ 3, 12]])

In [81]:
# Ordenando o array
np.sort(arr_index2d)

array([[ 2,  3,  4,  5],
       [-1,  0,  9, 10],
       [-4,  3,  8, 12],
       [-2,  0,  6,  7]])

In [82]:
# Podemos ordenar o array por linha (padrão) ou por coluna. 
# O eixo 1 representa a ordenção por linha e eixo 0 a ordenação por coluna.

np.sort(arr_index2d, axis = 0)

array([[ 0,  3, -4, -2],
       [ 2,  6, -1,  0],
       [ 3, 10,  5,  4],
       [ 9, 12,  7,  8]])

## Exercícios

### Explorando Ecossistemas:

Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas. considere a seguinte ordem de colunas:

ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie

* Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array como 'qtd_especies'
* De qtd_especies, selecione apenas as primeiras quantidades e print
* Printe as 5 últimas quantidades de espécies
* Crie um array que contenha apenas os tamanhos das especies e ordene por ordem crescente

In [159]:
especies = np.array([[747, 89,  33, 5],
                     [623, 123, 32, 13],
                     [501, 22,  49, 2],
                     [116, 101, 42, 10],
                     [297, 56,  69, 22],
                     [613, 64,  27, 7],
                     [295, 84,  29, 14],
                     [692, 105, 72, 16],
                     [229, 103, 35, 5],
                     [374, 124, 70, 1]])

In [160]:
# Selecione a segunda coluna com a quantidade de espécies 
# encontradas e adicione em um array como 'qtd_especies'

qtd_especies = especies[:, 1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [161]:
# De qtd_especies, selecione apenas as primeiras quantidades e printe
qtd_especies[0:3]

array([ 89, 123,  22])

In [162]:
# Printe as 5 últimas quantidades de espécies
qtd_especies[-5:]

array([ 64,  84, 105, 103, 124])

In [163]:
# Crie um array que contenha apenas os tamanhos das especies e 
# ordene por ordem crescente

tamanho_especies = np.sort(especies[:, 3])
tamanho_especies

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

## Filtragem de arrays

In [93]:
# Declarando o array

pessoas_id_idade = np.array([[1,22], [2,11], [3, 27], [4, 26]])

In [98]:
# Filtrando por máscara (mask) e indexação sofisticada (fancy indexing)

mask = pessoas_id_idade[:, 1] % 2 == 0
mask

pessoas_id_idade[mask]

array([[ 1, 22],
       [ 4, 26]])

In [100]:
# Filtrando por np.where()

indices = np.where(pessoas_id_idade[:, 1] % 2 == 0)
indices

pessoas_id_idade[indices]

array([[ 1, 22],
       [ 4, 26]])

In [102]:
# O np.where() pode ser interpretado como um if
# np.where(condicao, caso seja verdadeiro, caso seja falso)

cartela_bingo = np.array([
        [11,  3, 15],
        [ 2, 10,  7],
        [ 9, 22, 13],
        [ 6, 24, 27]])

In [104]:
# Ache os valores que são divisíveis por 3 na cartela e substitua por div3

np.where(cartela_bingo % 3 == 0, "div3", cartela_bingo)

array([['11', 'div3', 'div3'],
       ['2', '10', '7'],
       ['div3', '22', '13'],
       ['div3', 'div3', 'div3']], dtype='<U21')

## Exercícios

### Ainda sobre as espécies marítimas.

* Usando um index booleano, crie um array que contém os da maior espécie encontrada (considerando o seu tamanho). Esse valor corresponde ao valor 22.
* Usando o fancy indexing, faça um array que contém apenas dados da espécie com ID 297
* Usando np.where(), faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
* Considere a profundeza em que a espécies foi encontrada e substitua valores maiores que 6o com "Profundo"

In [108]:
# Usando um index booleano, crie um array que contém os da maior espécie encontrada
# (considerando o seu tamanho). Esse valor corresponde ao valor 22.


maior_especie = especies[especies[:, 3] == 22]
maior_especie

array([[297,  56,  69,  22]])

In [109]:
# Usando o fancy indexing, faça um array que contém apenas 
# dados da espécie com ID 297

mask_id297 = especies[:, 0] == 297

especies[mask_id297]

array([[297,  56,  69,  22]])

In [112]:
# Usando np.where(), faça um array com a linha com dados correspondentes 
# a espécie com 105 representantes encontrados.

indices_105 = np.where(especies[:, 1] == 105)

especies[indices_105]

array([[692, 105,  72,  16]])

In [116]:
# Considere a profundeza em que a espécies foi encontrada e substitua valores
#  maiores que 60 com "Profundo"

maior_60 = np.where(especies[:, 2] > 60, "Profundo", especies[: , 2])

maior_60

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U21')

## Concatenar arrays

In [120]:
# Arrays para concatenação

arr_concatenar1 = np.random.randint(10, size = (3,2))
arr_concatenar2 = np.array([["Uvas", "Morangos"]])
arr_concatenar3 = np.array([
                    ["Abacaxis"],
                    ["Maçãs"],
                    ["Bananas"]])

In [119]:
# Concatenando linhas
np.concatenate((arr_concatenar1, arr_concatenar2))

array([['8', '2'],
       ['3', '8'],
       ['1', '2'],
       ['Uvas', 'Morangos']], dtype='<U21')

In [122]:
# Concatenando colunas
np.concatenate((arr_concatenar1, arr_concatenar3), axis = 1)

array([['6', '3', 'Abacaxis'],
       ['1', '7', 'Maçãs'],
       ['2', '3', 'Bananas']], dtype='<U21')

## Deletando valores dos arrays

In [123]:
# Criação do array

sala_espera = np.array([
                ['5', '30', '1', 'Alice'],
                ['6', '29', '1', 'Bob'],
                ['7', '35', '3', 'Cristina'],
                ['8', '34', '3', 'Luiz']])

In [124]:
# Deletando linhas
np.delete(sala_espera, 1, axis = 0)

array([['5', '30', '1', 'Alice'],
       ['7', '35', '3', 'Cristina'],
       ['8', '34', '3', 'Luiz']], dtype='<U8')

In [125]:
# Deletando colunas
np.delete(sala_espera, 1, axis = 1)

array([['5', '1', 'Alice'],
       ['6', '1', 'Bob'],
       ['7', '3', 'Cristina'],
       ['8', '3', 'Luiz']], dtype='<U8')

## Fazendo cálculos com arrays

In [126]:
# Criação do array onde as linhas representam anos e colunas clientes

acidentes = np.array([
                [1, 3, 2],
                [0, 1, 0],
                [2, 1, 4],
                [0, 0, 0],
                [1, 1, 0]])

In [127]:
# Calcular a soma dos acidentes em todo o período

acidentes.sum()

16

In [128]:
# Calcular a soma por clientes (colunas)
acidentes.sum(axis = 0)

array([4, 6, 6])

In [129]:
# Calcular a soma por anos (linhas)
acidentes.sum(axis = 1)

array([6, 1, 7, 0, 2])

In [130]:
# Calcular o máximo de acidentes 
acidentes.max()

4

In [131]:
# Calcular o máximo de acidentes por cliente (colunas)
acidentes.max(axis = 0)

array([2, 3, 4])

In [132]:
# Calcular o máximo de acidentes por ano (linhas)
acidentes.max(axis = 1)

array([3, 1, 4, 0, 1])

In [133]:
# O mesmo cálculo de máximo, vale para o mínimo

acidentes.min(axis = 1)

array([1, 0, 1, 0, 0])

In [134]:
# Calcular a média de acidentes ao todo
acidentes.mean()

1.0666666666666667

In [135]:
# Calcular a média de acidentes por cliente (colunas)
acidentes.mean(axis = 0)

array([0.8, 1.2, 1.2])

In [136]:
# Calcular a média de acidentes por aluno (linhas)
acidentes.mean(axis = 1)

array([2.        , 0.33333333, 2.33333333, 0.        , 0.66666667])

In [137]:
# Calcular a soma acumulative de acidentes por cliente (colunas)
acidentes.cumsum(axis = 0)

array([[1, 3, 2],
       [1, 4, 2],
       [3, 5, 6],
       [3, 5, 6],
       [4, 6, 6]])

In [138]:
# Calcular a soma acumulative de acidentes por ano (linhas)
acidentes.cumsum(axis =1)

array([[1, 4, 6],
       [0, 1, 1],
       [2, 3, 7],
       [0, 0, 0],
       [1, 2, 2]])

## Exercícios

### Ainda no conjunto 'especies'

* Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]
* Adicione mais uma coluna no array agora com o número de espécies encontradas com que indica se o animal enxerga ou não:
[0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0]
* Faça um array com todas espécies menos as com ID: 623, 116, 613

In [164]:
# Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]

adicionar_2esp = [[204, 10, 40, 12], [392, 11, 81, 11]]

especies = np.concatenate((especies, adicionar_2esp))
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [168]:
# Adicione mais uma coluna no array agora com o número de espécies encontradas 
# com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0]

especies_enxergam = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1]).reshape(12,1)

especies = np.concatenate((especies, especies_enxergam), axis=1)
especies

array([[747,  89,  33,   5,   0,   0],
       [623, 123,  32,  13,   1,   1],
       [501,  22,  49,   2,   0,   0],
       [116, 101,  42,  10,   0,   0],
       [297,  56,  69,  22,   0,   0],
       [613,  64,  27,   7,   0,   0],
       [295,  84,  29,  14,   1,   1],
       [692, 105,  72,  16,   0,   0],
       [229, 103,  35,   5,   1,   1],
       [374, 124,  70,   1,   1,   1],
       [204,  10,  40,  12,   0,   0],
       [392,  11,  81,  11,   1,   1]])

In [170]:
# Faça um array com todas espécies menos as com ID: 623, 116, 613

ids_para_remover = [623, 116, 613]

indices_para_remover = np.where(np.isin(especies[:, 0], ids_para_remover))[0]

especies_filtrado = np.delete(especies, indices_para_remover, axis=0)

especies_filtrado


array([[747,  89,  33,   5,   0,   0],
       [501,  22,  49,   2,   0,   0],
       [297,  56,  69,  22,   0,   0],
       [295,  84,  29,  14,   1,   1],
       [692, 105,  72,  16,   0,   0],
       [229, 103,  35,   5,   1,   1],
       [374, 124,  70,   1,   1,   1],
       [204,  10,  40,  12,   0,   0],
       [392,  11,  81,  11,   1,   1]])